### ISSUE TITLE
error [python scripts/render_syn.py]

### ISSUE THREAD

**Issue by Kana-alt** [google/lasr#1]
I ran "python scripts/render_syn.py".

The following error has occurred. How can I solve this problem?

/home/kana/anaconda3/envs/lasr/lib/python3.8/site-packages/kornia/geometry/conversions.py:369: UserWarning: `XYZW` quaternion coefficient order is deprecated and will be removed after > 0.6. Please use `QuaternionCoeffOrder.WXYZ` instead.
  warnings.warn("`XYZW` quaternion coefficient order is deprecated and"
/home/kana/anaconda3/envs/lasr/lib/python3.8/site-packages/kornia/geometry/conversions.py:506: UserWarning: `XYZW` quaternion coefficient order is deprecated and will be removed after > 0.6. Please use `QuaternionCoeffOrder.WXYZ` instead.
  warnings.warn("`XYZW` quaternion coefficient order is deprecated and"

**Comment by gengshan-y** [comment]
Hi, this seems to be a warning and can be ignored.

**Comment by Kana-alt** [comment]
Thank you！！
