### ISSUE TITLE
how to plot such figure?

### ISSUE THREAD

**Issue by fangli333** [google/lasr#22]
hi,

can I know how to plot figure 2? Especially the colorful 3d mesh on the top right side of the figure 2? maybe which package you used. or which code snippets used by you in the repo. thank you!

bestanoy

**Comment by gengshan-y** [comment]
I believe the visualization of skinning weights is generated [here](https://github.com/google/lasr/blob/29d8759354f853119276f41504d6b527fd5484e5/extract.py#L204C72-L204C83), which is called by [this](https://github.com/google/lasr/blob/29d8759354f853119276f41504d6b527fd5484e5/scripts/render_result.sh#L18) script.

**Comment by fangli333** [comment]
> 

thank you for your reply. can i know which batchsize you used for such great performance?

**Comment by gengshan-y** [comment]
Hi, the details of optimization is included in the [supplement](https://openaccess.thecvf.com/content/CVPR2021/supplemental/Yang_LASR_Learning_Articulated_CVPR_2021_supplemental.pdf) of the paper

**Comment by fangli333** [comment]
> Hi, the details of optimization is included in the [supplement](https://openaccess.thecvf.com/content/CVPR2021/supplemental/Yang_LASR_Learning_Articulated_CVPR_2021_supplemental.pdf) of the paper

thank you!
