### ISSUE TITLE
why is N-NRSfM [44] not compared in Tab.3?

### ISSUE THREAD

**Issue by jason718** [google/lasr#9]
Thanks for the great work. What's the reason for not comparing to [44] in Tab.3 (mesh reconstruction)?

**Comment by gengshan-y** [comment]
Hi, N-NRSfM could be evaluated but the comparison would be unfair. 
Specifically N-NRSfM represents shape as an open surface (a sheet of paper) but the target mesh are closed surfaces.

**Comment by jason718** [comment]
thanks
